import nodemailer from 'nodemailer';

const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER || 'nivarnahealth@gmail.com',
    pass: process.env.EMAIL_PASSWORD || ''
  }
});

const generateStudyPlanHTML = (plan, isAdvanced = false) => {
  const sessionsHTML = (plan.dailySessions || []).map(session => `
    <tr>
      <td style="padding:12px 16px;border-bottom:1px solid #eee;font-weight:700;color:#6C3CE1;font-size:15px;vertical-align:top;width:70px;">
        Day ${session.day}
      </td>
      <td style="padding:12px 16px;border-bottom:1px solid #eee;">
        <div style="margin-bottom:6px;">
          ${(session.topics || []).map(t => `<span style="display:inline-block;background:#F3E8FF;color:#7C3AED;padding:3px 10px;border-radius:20px;font-size:12px;margin:2px 4px 2px 0;font-weight:600;">📌 ${t}</span>`).join('')}
        </div>
        <div style="color:#64748B;font-size:13px;">
          ${(session.activities || []).map(a => `<div style="margin:2px 0;">✏️ ${a}</div>`).join('')}
        </div>
        ${(session.resources || []).length > 0 ? `
        <div style="margin-top:6px;font-size:12px;color:#94A3B8;">
          ${session.resources.map(r => `<div>📚 ${r}</div>`).join('')}
        </div>` : ''}
      </td>
    </tr>
  `).join('');

  const videoSection = isAdvanced && plan.videoSummary ? `
    <div style="background:linear-gradient(135deg,#1E1B4B,#312E81);border-radius:16px;padding:24px;margin:24px 0;color:white;">
      <h3 style="margin:0 0 12px;font-size:18px;">🎬 Video Analysis</h3>
      <h4 style="margin:0 0 8px;font-size:15px;color:#A5B4FC;">${plan.videoSummary.title || 'Video Summary'}</h4>
      <p style="margin:0 0 16px;font-size:13px;line-height:1.6;color:#C7D2FE;">${plan.videoSummary.summary || ''}</p>
      ${plan.videoSummary.keyPoints?.length ? `
      <div style="background:rgba(255,255,255,0.1);border-radius:12px;padding:16px;">
        <h5 style="margin:0 0 8px;font-size:13px;color:#FDE68A;">🔑 Key Points</h5>
        ${plan.videoSummary.keyPoints.map(kp => `<div style="font-size:12px;color:#E0E7FF;margin:4px 0;">• ${kp}</div>`).join('')}
      </div>` : ''}
    </div>
  ` : '';

  const cardsSection = isAdvanced && plan.summaryCards?.length ? `
    <div style="margin:24px 0;">
      <h3 style="color:#1E293B;font-size:18px;margin:0 0 16px;">📋 Summary Cards</h3>
      <div style="display:flex;flex-wrap:wrap;gap:12px;">
        ${plan.summaryCards.map(card => `
          <div style="background:${card.color || '#8B5CF6'}15;border:2px solid ${card.color || '#8B5CF6'};border-radius:12px;padding:16px;width:calc(33% - 8px);min-width:180px;">
            <div style="font-size:24px;margin-bottom:6px;">${card.emoji || '💡'}</div>
            <div style="font-weight:700;font-size:13px;color:#1E293B;margin-bottom:4px;">${card.title}</div>
            <div style="font-size:12px;color:#64748B;">${card.keyPoint}</div>
          </div>
        `).join('')}
      </div>
    </div>
  ` : '';

  const chartsSection = isAdvanced && plan.charts?.length ? `
    <div style="margin:24px 0;">
      <h3 style="color:#1E293B;font-size:18px;margin:0 0 16px;">📊 Visual Charts</h3>
      ${plan.charts.map(chart => `
        <div style="background:#F8FAFC;border:1px solid #E2E8F0;border-radius:12px;padding:16px;margin-bottom:12px;">
          <h4 style="margin:0 0 8px;font-size:14px;color:#334155;">${chart.title}</h4>
          <div style="font-size:12px;color:#64748B;">Type: ${chart.type} | Data points: ${Array.isArray(chart.data) ? chart.data.length : 'N/A'}</div>
        </div>
      `).join('')}
    </div>
  ` : '';

  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#F1F5F9;font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;">
  <div style="max-width:640px;margin:0 auto;padding:24px;">
    <div style="background:linear-gradient(135deg,${isAdvanced ? '#6C3CE1,#3B82F6' : '#F59E0B,#EF4444'});border-radius:20px 20px 0 0;padding:32px 24px;text-align:center;">
      <h1 style="margin:0;color:white;font-size:28px;font-weight:800;letter-spacing:-0.5px;">
        ${isAdvanced ? '🚀' : '📚'} ${plan.title || 'Study Plan'}
      </h1>
      <p style="margin:8px 0 0;color:rgba(255,255,255,0.85);font-size:14px;">
        ${plan.totalDays || 7} Day${(plan.totalDays || 7) > 1 ? 's' : ''} • ${isAdvanced ? 'Advanced' : 'Normal'} Plan • Generated by SENSEI AI
      </p>
    </div>

    <div style="background:white;border-radius:0 0 20px 20px;padding:24px;box-shadow:0 4px 20px rgba(0,0,0,0.08);">
      ${videoSection}
      ${cardsSection}

      <h3 style="color:#1E293B;font-size:18px;margin:24px 0 16px;">📅 Daily Schedule</h3>
      <table style="width:100%;border-collapse:collapse;">
        ${sessionsHTML}
      </table>

      ${chartsSection}

      <div style="text-align:center;margin-top:32px;padding-top:24px;border-top:1px solid #E2E8F0;">
        <p style="color:#94A3B8;font-size:12px;margin:0;">
          Generated by <strong style="color:#6C3CE1;">SENSEI</strong> — AI-Powered Adaptive Learning Platform
        </p>
      </div>
    </div>
  </div>
</body>
</html>`;
};

export const sendStudyPlanEmail = async (recipientEmail, studentName, plan, isAdvanced = false) => {
  const html = generateStudyPlanHTML(plan, isAdvanced);
  const mailOptions = {
    from: `"SENSEI AI" <${process.env.EMAIL_USER || 'nivarnahealth@gmail.com'}>`,
    to: recipientEmail,
    subject: `${isAdvanced ? '🚀 Advanced' : '📚'} Study Plan: ${plan.title || 'Your Study Plan'} — SENSEI`,
    html
  };

  const info = await transporter.sendMail(mailOptions);
  return { messageId: info.messageId, accepted: info.accepted };
};

export default { sendStudyPlanEmail };
